### ISSUE TITLE
Where can I find the list of API?

### ISSUE THREAD

**Issue by tcst** [jmaddi/liftapp-client#3]
Hello, 

I came across your app while looking for Lift.do API to integrate with my app (using node js). Would you be able to share the list of available APIs of Lift.do? Thanks much.
- Vu

**Comment by jmaddi** [comment]
@tcst ,

You can see the API calls that this gem is using by looking at this file:
https://github.com/jmaddi/liftapp-client/blob/master/lib/liftapp-client.rb

I notice thought, that lift.do has changed to coach.me so let me know if it doesn't work anymore.

**Comment by tcst** [comment]
@jmaddi Thanks much :)

I will try those. If it doesn't work, do you know how I can look for the updated version? I'm not sure if they plan to (officially) support it in the future.

Thanks,
Vu

**Comment by jmaddi** [comment]
Hi @tcst 

It is actually quite easy now that they have a web interface. Log in to coach.me with Google Chrome, and open the web inspector at the network tab:

![image](https://cloud.githubusercontent.com/assets/947911/5894507/bf08ca30-a55c-11e4-9ffb-85e0622b9c46.png)

If you select XHR, you should be able to see all the requests the app is making.

**Comment by tcst** [comment]
Ah that's very smart. Thanks for the tip :+1:  :)
